services:
  db:
    image: docker.io/library/postgres:15
    container_name: postgres-reserva-compose
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: reservas_db
    ports:
      - "5455:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d reservas_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: reserva-api-compose
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+psycopg2://admin:admin@db:5432/reservas_db
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    restart: unless-stopped

  redis:
    image: docker.io/library/redis:7-alpine
    container_name: redis-reserva-compose
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  db_data:
